plugins {
    id 'com.android.application'
}

android {
    compileSdk = 37
    namespace "com.javacakegames.pride"

    defaultConfig {
        applicationId "com.javacakegames.pride"
        minSdk 1
        targetSdk 37
        versionCode 62
        versionName "6.2"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

}